dist: xenial
language: python
python:
  - '3.7'
stages:
  - build
  - static-checks
  - test
jobs:
  include:
    - stage: build
      script:
        - python setup.py install
    - stage: static-checks
      script:
        - flake8 loggo/ tests/ setup.py
        - mypy loggo/ tests/ setup.py
        - black --check .
    - stage: test
      script:
        - coverage run -m unittest
        - codecov
