dist: xenial
language: python
python:
  - '3.7'
jobs:
  include:
    - name: build
      script:
        - python setup.py install
    - name: static-checks
      script:
        - flake8 loggo/ tests/ setup.py
        - mypy loggo/ tests/ setup.py
        - black --check .
    - name: test
      script:
        - coverage run -m unittest
        - coverage report --fail-under=95
        - codecov
