dist: xenial
language: python
python:
  - '3.6'
  - '3.7'
  - '3.8-dev'
script:
  # Build
  - python setup.py install
  # Static checks (only in Python 3.6 job)
  - |
    if [[ $TRAVIS_PYTHON_VERSION == '3.6' ]]; then
      flake8 . &&
      mypy . &&
      black --check .
    fi
  # Tests
  - coverage run -m unittest
  - coverage report --fail-under=95
  # Upload coverage (only in Python 3.6 job)
  - if [[ $TRAVIS_PYTHON_VERSION == '3.6' ]]; then codecov; fi
