dist: xenial
language: python
python:
  - '3.7'
stages:
  - build
  - test
jobs:
  include:
    - stage: build
      script:
        - python setup.py install
    - stage: test
      script:
        - flake8 loggo/ tests/
        - mypy loggo/ tests/
        - python setup.py install
        - python tests/tests.py
